[workspace]
members = [
    "bot",
    "vived/*"
]

[workspace.dependencies]
log = "0.4"
tokio = {version = "1.21", default-features = false}
serde = {version = "1.0"}
serde_json = "*"
chrono = "0.4"

[profile.release]
lto = true
strip="debuginfo"